"""tabela atualizada

Revision ID: b22e26154a47
Revises: 
Create Date: 2026-06-17 16:02:24.624576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22e26154a47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuarios_acesso_key'), 'usuarios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('usuarios_acesso_key'), 'usuarios', ['acesso'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
