name: Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      CLIENT_ID: "1"
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ALLOW_ORIGINS: ${{ secrets.ALLOW_ORIGINS }}

    defaults:
      run:
        working-directory: ./beck

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
        
      - name:  Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install --no-root

      - name: Executar testes
        run: poetry run task test  
        